apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: "registry.hub.docker.com/870414/intro:latest"
      # --- BEGIN ---
      readinessProbe: # Добавим проверку готовности
        httpGet: # веб-сервера отдавать
          path: /index.html # контент
          port: 80
      # --- END ---
      livenessProbe:
        tcpSocket: { port: 8000 }
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: busybox
      image: busybox:1.31.0
      command: ["sh", "-c", "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
